"""Why the author must not grade its own homework, demonstrated mechanically.

The literature on self-preference is about judgement: evaluators score their
own generations higher, and the effect tracks how familiar the text looks
rather than how good it is. The deep dive cites it.

This file is about something narrower and fully checkable in a test suite: a
suite derived from an implementation's behaviour cannot detect that the
behaviour is wrong. No model is involved and none is needed. It is a property
of where the assertions came from, and it holds for a human who writes tests by
running the code and pasting the output.

Two demonstrations:

  the shared-belief trap    one wrong assumption, expressed in both the parser
                            and its tests. The pair is self-consistent, green,
                            and wrong. Only an independent reference notices.
  the characterization trap tests generated by observing the implementation.
                            They pin behaviour perfectly and say nothing about
                            whether the behaviour is correct.

The independent reference is the UF2 specification, restated here from the
field layout rather than from fwvault's constants. tests/test_differential.py
already asserts that its reference borrows nothing from the implementation; the
last test here asserts the same for this one, because an oracle that imports the
thing it checks is not an oracle.
"""

import re
import struct

import pytest

from fwvault.errors import ParseError
from fwvault.parse import UF2_PAYLOAD_MAX, parse
from fwvault.testing import RP2040, build_uf2

# The spec value, written out rather than imported. A UF2 block is 512 bytes:
# 32 of header, 4 of trailing magic, and 476 of payload. If this file imported
# UF2_PAYLOAD_MAX it would agree with the implementation by construction and
# check nothing.
SPEC_BLOCK = 512
SPEC_HEADER = 32
SPEC_TRAILER = 4
SPEC_PAYLOAD_MAX = SPEC_BLOCK - SPEC_HEADER - SPEC_TRAILER      # 476

# The wrong belief: that a block's payload is everything after the header.
# Plausible, off by the four trailing magic bytes, and the kind of thing an
# author infers from a diagram instead of reading the field table.
BELIEF_PAYLOAD_MAX = SPEC_BLOCK - SPEC_HEADER                   # 480


# ── the shared-belief trap ──────────────────────────────────────────────────

def parser_from_belief(blob):
    """A parser written by someone holding the wrong belief.

    Identical to the real one except for the clamp, which is the belief made
    executable.
    """
    from dataclasses import replace

    image = parse(blob)
    blocks = len(blob) // SPEC_BLOCK
    declared = [struct.unpack_from("<I", blob, i * SPEC_BLOCK + 16)[0]
                for i in range(blocks)]
    payload = sum(min(size, BELIEF_PAYLOAD_MAX) for size in declared)
    warnings = tuple(w for w in image.warnings if "exceeds" not in w)
    if any(size > BELIEF_PAYLOAD_MAX for size in declared):
        warnings += ("payloadSize exceeds %d, clamped" % BELIEF_PAYLOAD_MAX,)
    return replace(image, payload_bytes=payload, warnings=warnings)


def suite_from_belief(parse_fn):
    """Tests written by the same author, from the same belief.

    Named `suite_from_belief` and not `tests_from_belief` because pytest
    collects anything matching `test*`, helper or not, and would try to inject
    `parse_fn` as a fixture. The field card documents this; it still caught
    this file.

    Careful, specific, and asserting positively. Everything the previous file
    argues for. They are still wrong, because the number in them came from the
    same place the number in the parser came from.
    """
    over = build_uf2(blocks=1, family=RP2040, oversized_payload=9999)
    image = parse_fn(over)
    assert image.payload_bytes == BELIEF_PAYLOAD_MAX
    assert any("clamped" in w for w in image.warnings)

    ordinary = parse_fn(build_uf2(blocks=2, family=RP2040, payload_size=256))
    assert ordinary.payload_bytes == 512


def passes(suite, parse_fn):
    try:
        suite(parse_fn)
    except BaseException:
        return False
    return True


def test_the_belief_pair_is_self_consistent():
    """Green. A suite and an implementation that agree with each other always
    are, and no amount of care in either one changes that."""
    assert passes(suite_from_belief, parser_from_belief)


def test_the_belief_pair_is_wrong():
    """And the belief is genuinely wrong: the same tests fail against the real
    parser, which clamps at the spec value."""
    assert not passes(suite_from_belief, parse)


def test_only_the_independent_reference_notices():
    """The spec, restated from the field layout, catches what the pair cannot.

    This is the whole argument for provenance separation stated as an
    assertion: the check has to come from somewhere the implementation did not.
    """
    over = build_uf2(blocks=1, family=RP2040, oversized_payload=9999)

    assert parse(over).payload_bytes == SPEC_PAYLOAD_MAX
    assert parser_from_belief(over).payload_bytes == BELIEF_PAYLOAD_MAX
    assert SPEC_PAYLOAD_MAX != BELIEF_PAYLOAD_MAX


def test_the_specs_constant_and_the_packages_agree():
    """The reference is only worth anything if it is right. Derived from the
    block layout here, imported there, and they have to match."""
    assert SPEC_PAYLOAD_MAX == UF2_PAYLOAD_MAX == 476


# ── the characterization trap ───────────────────────────────────────────────

def characterize(parse_fn, blobs):
    """Generate assertions by running the implementation and recording what it
    said. This is what "write tests for this function" produces when the author
    has no independent notion of the right answer.
    """
    recorded = []
    for blob in blobs:
        try:
            image = parse_fn(blob)
            recorded.append((blob, "ok", image.payload_bytes, image.block_count))
        except ParseError:
            recorded.append((blob, "raised", None, None))

    def suite(candidate):
        for blob, outcome, payload, blocks in recorded:
            try:
                image = candidate(blob)
            except ParseError:
                assert outcome == "raised"
                continue
            assert outcome == "ok"
            assert image.payload_bytes == payload
            assert image.block_count == blocks

    return suite


SPECIMENS = [
    build_uf2(blocks=3, family=RP2040),
    build_uf2(blocks=1, family=RP2040, oversized_payload=9999),
    build_uf2(blocks=2, bad_end_magic=1),
    b"",
    b"\x00" * 64,
]


def test_characterization_tests_always_pass_against_their_source():
    """By construction. They were transcribed from it."""
    assert passes(characterize(parse, SPECIMENS), parse)


def test_characterization_tests_pass_against_a_wrong_implementation_too():
    """The finding.

    Generate the suite from the WRONG parser and it is just as green against
    that parser. The process cannot distinguish a correct implementation from
    an incorrect one, because at no point does anything outside the
    implementation enter the loop.
    """
    from_wrong = characterize(parser_from_belief, SPECIMENS)
    assert passes(from_wrong, parser_from_belief)
    assert not passes(from_wrong, parse)


def test_characterization_tests_do_catch_change():
    """What they are actually good for, stated so the file is not a hit piece.

    A characterization suite is a regression harness: it detects that behaviour
    moved. That is genuinely useful before a refactor. It is not a correctness
    check, and the failure is treating one as the other.
    """
    from dataclasses import replace

    def drifted(blob):
        return replace(parse(blob), block_count=99)

    assert not passes(characterize(parse, SPECIMENS), drifted)


# ── provenance, asserted ────────────────────────────────────────────────────

def test_this_files_reference_borrows_nothing_from_the_implementation():
    """An oracle that imports the thing it checks agrees with it by
    construction.

    The one import of a package constant is in
    `test_the_specs_constant_and_the_packages_agree`, which exists to compare
    the two and would be pointless without it. Everywhere else the spec value
    is derived from the block layout.
    """
    import pathlib

    source = pathlib.Path(__file__).read_text(encoding="utf-8")
    body = source[source.index("SPEC_BLOCK = 512"):]

    derivation = body[body.index("SPEC_PAYLOAD_MAX = "):body.index(chr(10), body.index("SPEC_PAYLOAD_MAX = "))]
    assert "UF2_PAYLOAD_MAX" not in derivation, (
        "the spec constant is imported rather than derived, so the reference "
        "cannot disagree with the implementation")

    # exclude this function's own body, which necessarily names the constant
    own = source.index("def test_this_files_reference_borrows_nothing")
    outside = source[:own].splitlines()
    uses = [n for n, line in enumerate(outside, 1)
            if "UF2_PAYLOAD_MAX" in line and not line.strip().startswith("#")]
    assert len(uses) <= 2, (
        "the package constant leaked into the reference at lines %s" % uses)


def test_the_two_references_in_this_repo_are_not_the_same_code():
    """tests/test_differential.py has its own reference walker. Two independent
    references are only worth two if they were written differently; if one was
    copied from the other, the repo has one reference and a duplicate.
    """
    import pathlib

    here = pathlib.Path(__file__).parent
    mine = (here / "test_oracle_independence.py").read_text(encoding="utf-8")
    theirs = (here / "test_differential.py").read_text(encoding="utf-8")

    def shingles(text):
        words = re.findall(r"[A-Za-z_]+", text)
        return {tuple(words[i:i + 8]) for i in range(len(words) - 8)}

    a, b = shingles(mine), shingles(theirs)
    overlap = len(a & b) / min(len(a), len(b))
    assert overlap < 0.10, (
        "the two references share %.0f%% of their 8-word sequences, which "
        "makes them one reference with two names" % (overlap * 100))
